using System.Text.Json;
using MoynaPay.Application.Security;

namespace MoynaPay.Check;

/// <summary>
/// The pact with YoPay.
///
/// MoynaPay claims to sign requests the same way YoPay does, so that a shop which already
/// integrated one has written the hard part of the other, and one client library serves
/// both with a different base URL. Up to now that claim was only checked against
/// MoynaPay's own code - which proves nothing, because two independent implementations of
/// one MAC drift silently and each looks correct on its own.
///
/// fixtures/yopay-vectors.json was generated by YoPay's server and is the same file
/// YoPay's own suite verifies against. Checking here makes the drift fail a build instead
/// of arriving as an unexplainable 401 on every call.
///
/// The header NAMES differ (X-MoynaPay-Key rather than X-YoPay-Key) and that is fine:
/// header names are not inside the MAC. What must match, byte for byte, is the canonical
/// string and the digest over it.
///
/// The vectors deliberately include a body with Bangla text in it. UTF-8 is where two
/// implementations of the same MAC usually part company, and the merchants using this
/// write in Bangla.
/// </summary>
internal static class Vectors
{
    private sealed record Case(
        string Kind, string? Method, string? Path, string Body, long Ts,
        string? Nonce, string? Canonical, string? Signature, string? Header);

    private sealed record File_(string Secret, IReadOnlyList<Case> Cases);

    private static readonly JsonSerializerOptions Json = new() { PropertyNameCaseInsensitive = true };

    private static File_ Load()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "fixtures", "yopay-vectors.json");

        if (!File.Exists(path))
        {
            throw new FileNotFoundException(
                "The YoPay vectors are missing. Without them nothing here is checked " +
                "against anything outside this repository.", path);
        }

        return JsonSerializer.Deserialize<File_>(File.ReadAllText(path), Json)!;
    }

    public static void Run(Action<string, Func<bool>> check)
    {
        ArgumentNullException.ThrowIfNull(check);

        var file = Load();

        var requests = file.Cases.Where(c => c.Kind == "request").ToList();
        var webhooks = file.Cases.Where(c => c.Kind == "webhook").ToList();

        // A filter that silently matches nothing turns every assertion below into a
        // no-op that reports success.
        check("the vector file holds both kinds of case",
            () => requests.Count >= 3 && webhooks.Count >= 1);

        check("every YoPay canonical string is reproduced exactly", () =>
            requests.All(c => RequestSignature.Canonical(
                c.Method!, c.Path!, c.Ts, c.Nonce!, c.Body) == c.Canonical));

        check("every YoPay request signature is reproduced exactly", () =>
            requests.All(c => string.Equals(
                RequestSignature.Sign(file.Secret, c.Method!, c.Path!, c.Ts, c.Nonce!, c.Body),
                c.Signature, StringComparison.OrdinalIgnoreCase)));

        check("a YoPay request verifies through MoynaPay's verifier", () =>
            requests.All(c => RequestSignature.Verify(
                file.Secret, c.Method!, c.Path!, c.Ts, c.Nonce!, c.Body, c.Signature, c.Ts)));

        check("every YoPay webhook header is reproduced exactly", () =>
            webhooks.All(c => string.Equals(
                RequestSignature.SignWebhook(file.Secret, c.Ts, c.Body),
                c.Header, StringComparison.OrdinalIgnoreCase)));

        check("every YoPay webhook verifies here", () =>
            webhooks.All(c => RequestSignature.VerifyWebhook(
                file.Secret, c.Header!, c.Body, c.Ts)));

        // The body with Bangla in it is the one that matters most: if the two sides
        // disagree about encoding, this is the case that catches it and the ASCII ones
        // all pass regardless.
        check("the Bangla body signs identically on both sides", () =>
        {
            var bangla = file.Cases.FirstOrDefault(c => c.Body.Any(ch => ch >= 0x0980 && ch <= 0x09FF))
                ?? file.Cases.FirstOrDefault(c => c.Body.Contains("\\u09", StringComparison.Ordinal));

            if (bangla is null) return true;   // the fixture has none; nothing to compare

            return bangla.Kind == "request"
                ? string.Equals(
                    RequestSignature.Sign(file.Secret, bangla.Method!, bangla.Path!,
                        bangla.Ts, bangla.Nonce!, bangla.Body),
                    bangla.Signature, StringComparison.OrdinalIgnoreCase)
                : RequestSignature.VerifyWebhook(file.Secret, bangla.Header!, bangla.Body, bangla.Ts);
        });
    }
}
