// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoynaPay.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoynaPay.Infrastructure.Migrations
{
    [DbContext(typeof(MoynaPayDbContext))]
    [Migration("20260930112152_MerchantSipTrunks")]
    partial class MerchantSipTrunks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("moynapay")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoynaPay.Application.Abstractions.AppDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("app_version");

                    b.Property<int?>("BatteryPercent")
                        .HasColumnType("integer")
                        .HasColumnName("battery_percent");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_token_hash");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("fingerprint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NetworkType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("network_type");

                    b.Property<string>("PermissionState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("permission_state");

                    b.Property<string>("PushToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("push_token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_app_devices");

                    b.HasIndex("Id", "DeviceTokenHash")
                        .HasDatabaseName("ix_app_devices_id_device_token_hash");

                    b.HasIndex("MerchantId", "LastHeartbeatAt")
                        .HasDatabaseName("ix_app_devices_merchant_id_last_heartbeat_at");

                    b.ToTable("app_devices", "merchants");
                });

            modelBuilder.Entity("MoynaPay.Application.Abstractions.AppDevicePairingToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_app_device_pairing_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_app_device_pairing_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_app_device_pairing_tokens_token_hash");

                    b.ToTable("app_device_pairing_tokens", "merchants");
                });

            modelBuilder.Entity("MoynaPay.Application.Abstractions.AppOtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Msisdn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("msisdn");

                    b.HasKey("Id")
                        .HasName("pk_app_otp_challenges");

                    b.HasIndex("Msisdn", "CreatedAt")
                        .HasDatabaseName("ix_app_otp_challenges_msisdn_created_at");

                    b.ToTable("app_otp_challenges", "merchants");
                });

            modelBuilder.Entity("MoynaPay.Application.Abstractions.AppToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("ReplacedByHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_app_tokens");

                    b.HasIndex("MerchantId", "ExpiresAt")
                        .HasDatabaseName("ix_app_tokens_merchant_id_expires_at");

                    b.HasIndex("TokenHash", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_app_tokens_token_hash_kind");

                    b.ToTable("app_tokens", "merchants");
                });

            modelBuilder.Entity("MoynaPay.Application.Abstractions.WorkflowAction", b =>
                {
                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("ActionId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<string>("Result")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("MerchantId", "OrderId", "ActionId")
                        .HasName("pk_workflow_actions");

                    b.ToTable("workflow_actions", "orders");
                });

            modelBuilder.Entity("MoynaPay.Application.Abstractions.WorkflowSession", b =>
                {
                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("complete");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("history");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lease_until");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("step");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("MerchantId", "OrderId", "Name")
                        .HasName("pk_workflow_sessions");

                    b.HasIndex("Name", "Complete", "LeaseUntil")
                        .HasDatabaseName("ix_workflow_sessions_name_complete_lease_until");

                    b.ToTable("workflow_sessions", "orders");
                });

            modelBuilder.Entity("MoynaPay.Domain.Merchants.ApiCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_id");

                    b.Property<string>("KeyRingId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_ring_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SecretCipher")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("secret_cipher");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_api_credentials");

                    b.HasIndex("KeyId")
                        .IsUnique()
                        .HasDatabaseName("ix_api_credentials_key_id");

                    b.ToTable("api_credentials", "merchants");
                });

            modelBuilder.Entity("MoynaPay.Domain.Merchants.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Msisdn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("msisdn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SupportMsisdn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("support_msisdn");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_merchants");

                    b.HasIndex("Msisdn")
                        .IsUnique()
                        .HasDatabaseName("ix_merchants_msisdn")
                        .HasFilter("is_deleted = false");

                    b.ToTable("merchants", "merchants");
                });

            modelBuilder.Entity("MoynaPay.Domain.Merchants.RateLimitHit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamptz")
                        .HasColumnName("at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rate_limit_hits");

                    b.HasIndex("Key", "At")
                        .HasDatabaseName("ix_rate_limit_hits_key_at");

                    b.ToTable("rate_limit_hits", "merchants");
                });

            modelBuilder.Entity("MoynaPay.Domain.Merchants.RequestNonce", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_id");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nonce");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("seen_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_request_nonces");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_request_nonces_expires_at");

                    b.HasIndex("KeyId", "Nonce")
                        .IsUnique()
                        .HasDatabaseName("ix_request_nonces_key_id_nonce");

                    b.ToTable("request_nonces", "merchants");
                });

            modelBuilder.Entity("MoynaPay.Domain.Merchants.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Calls")
                        .HasColumnType("boolean")
                        .HasColumnName("calls");

                    b.Property<bool>("Courier")
                        .HasColumnType("boolean")
                        .HasColumnName("courier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("Payments")
                        .HasColumnType("boolean")
                        .HasColumnName("payments");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("plan");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_tenant_id")
                        .HasFilter("is_deleted = false");

                    b.ToTable("subscriptions", "merchants");
                });

            modelBuilder.Entity("MoynaPay.Domain.Merchants.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("KeyRingId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_ring_id");

                    b.Property<DateTimeOffset?>("LastDeliveredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_delivered_at");

                    b.Property<string>("LastFailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_failure_reason");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SecretCipher")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("secret_cipher");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_webhook_endpoints");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_webhook_endpoints_tenant_id");

                    b.ToTable("webhook_endpoints", "merchants");
                });

            modelBuilder.Entity("MoynaPay.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("CallAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("call_attempts");

                    b.Property<string>("CallbackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("callback_url");

                    b.Property<decimal?>("ChargedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("charged_amount");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset?>("ClaimedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("claimed_until");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("Courier")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("courier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("customer_name");

                    b.Property<string>("Digit")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("digit");

                    b.Property<string>("FieldsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("fields_json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastCallAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_call_attempt_at");

                    b.Property<string>("Msisdn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("msisdn");

                    b.Property<DateTimeOffset?>("NextCallAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_call_attempt_at");

                    b.Property<decimal?>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("paid_amount");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("paid_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reference");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("shipped_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TrackingCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tracking_code");

                    b.Property<string>("TrxId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trx_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("TenantId", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_tenant_id_reference")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_orders_tenant_id_status_created_at");

                    b.HasIndex("TenantId", "Status", "NextCallAttemptAt")
                        .HasDatabaseName("ix_orders_tenant_id_status_next_call_attempt_at");

                    b.ToTable("orders", "orders");
                });

            modelBuilder.Entity("MoynaPay.Domain.Orders.OrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor");

                    b.Property<string>("ActorName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor_name");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamptz")
                        .HasColumnName("at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("From")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("To")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_order_events");

                    b.HasIndex("OrderId", "At")
                        .HasDatabaseName("ix_order_events_order_id_at");

                    b.ToTable("order_events", "orders");
                });

            modelBuilder.Entity("MoynaPay.Domain.Orders.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset?>("ClaimedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("claimed_until");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("delivered_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsDead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dead");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastFailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_failure_reason");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ClaimedBy")
                        .HasDatabaseName("ix_outbox_messages_claimed_by")
                        .HasFilter("claimed_by is not null");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_next_attempt_at")
                        .HasFilter("delivered_at is null and is_dead = false");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_order_id_created_at")
                        .HasFilter("delivered_at is null and is_dead = false");

                    b.ToTable("outbox_messages", "orders");
                });

            modelBuilder.Entity("MoynaPay.Domain.Payments.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CallbackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("callback_url");

                    b.Property<decimal>("ChargedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("charged_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerMsisdn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_msisdn");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("customer_name");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GraceUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("grace_until");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("order_ref");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("paid_at");

                    b.Property<string>("RedirectUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("redirect_url");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("TenantId", "OrderRef")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_tenant_id_order_ref")
                        .HasFilter("is_deleted = false");

                    b.ToTable("invoices", "payments");
                });

            modelBuilder.Entity("MoynaPay.Domain.Voice.SipTrunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("auth_mode");

                    b.Property<string>("CallerId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("caller_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("host");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SecretStoreReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("secret_store_reference");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_sip_trunks");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_sip_trunks_tenant_id_is_active");

                    b.ToTable("sip_trunks", "telephony");
                });
#pragma warning restore 612, 618
        }
    }
}
