[global]
type = global
user_agent = MoynaPayLocalAsterisk

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[1001]
type = endpoint
transport = transport-udp
context = from-softphone
disallow = all
allow = ulaw,alaw,slin16
auth = 1001
aors = 1001
direct_media = no
dtmf_mode = rfc4733
rewrite_contact = yes
force_rport = yes
rtp_symmetric = yes

[1001]
type = auth
auth_type = userpass
username = 1001
password = 1001

[1001]
type = aor
max_contacts = 1
remove_existing = yes
qualify_frequency = 30
